#!/bin/bash
# ---------------------------------------------------------------------------
# LOCAL (no-sbatch) dedicated BR sweep: 20 evenly-spaced spar_Ve_Bl checkpoints.
#
# Runs br_slurm_orchestrator.py in its local fallback (no sbatch on this box):
# it claims each .task from --todo_dir, builds per-(state x direction) BR jobs,
# and runs each as `bash <auto-generated script>` throttled by --max_local_concurrent.
#
# ENV IS MATCHED TO HOW THESE SPAR CHECKPOINTS WERE TRAINED (joint decision timing):
#   decision_timing joint / actionable_statuses 512,514,520 / dwell_frames 4
#   transform_action True / reward_scale 1.0 (unscaled) / enable_combo True
# (max_skip_frames 90 is already the env default.) decision_timing is passed
# EXPLICITLY (not 'auto'), so the arch-guess warning does NOT fire -- this value
# is known-correct, not guessed.
#
# Set DRY_RUN=True to print the job plan + write the per-job scripts WITHOUT
# executing (foreground). Default runs for real, backgrounded with nohup.
# ---------------------------------------------------------------------------
set -u

REPO_DIR=/home/jw4406/codebase/FightLadder
cd "$REPO_DIR"

TASKS="$REPO_DIR/main/trained_models/tasks"
TODO_DIR="$TASKS/todo_br20"
PROCESSING_DIR="$TASKS/processing_br20"
DONE_DIR="$TASKS/done_br20"
STOP_FILE="$TASKS/STOP_BR20"
LOCAL_PLOT_DIR="$REPO_DIR/logs/local_entropy_plots"
SLURM_LOG_DIR="$REPO_DIR/logs/br_br20_logs"      # per-job .out/.err/.sbatch land here
LOGS_DIR="$REPO_DIR/logs"
mkdir -p "$PROCESSING_DIR" "$DONE_DIR" "$LOCAL_PLOT_DIR" "$SLURM_LOG_DIR" "$LOGS_DIR"

BR_TRAINING_STEPS=3000000       # 3M .learn() timesteps per BR job
DRY_RUN="${DRY_RUN:-False}"

# Activate the env inside each auto-generated per-job bash script.
ENV_SETUP='source /home/jw4406/anaconda3/etc/profile.d/conda.sh && conda activate fightladder'

CMD=(python -u "$REPO_DIR/main/br_slurm_orchestrator.py"
	--todo_dir "$TODO_DIR"
	--processing_dir "$PROCESSING_DIR"
	--done_dir "$DONE_DIR"
	--stop_file "$STOP_FILE"
	--local_plot_dir "$LOCAL_PLOT_DIR"
	--slurm_log_dir "$SLURM_LOG_DIR"
	--env_setup "$ENV_SETUP"
	--br_training_steps "$BR_TRAINING_STEPS"
	--num_full_exploiters 1
	--eval_prot True
	--eval_adv True
	--max_local_concurrent 2
	--step_stride 0
	--decision_timing joint
	--actionable_statuses 512,514,520
	--dwell_frames 4
	--transform_action True
	--reward_scale 1.0
	--enable_combo True
)

if [ "$DRY_RUN" = "True" ]; then
	CMD+=(--dry_run True)
	echo "=== DRY RUN: printing plan + writing per-job scripts, NO execution ==="
	"${CMD[@]}"
else
	echo "Starting LOCAL dedicated BR orchestrator (20x spar_Ve_Bl, 3M steps, joint)..."
	nohup "${CMD[@]}" > "${LOGS_DIR}/br_dedicated_local_Ve_Bl_20.log" 2>&1 &
	echo "Orchestrator started with PID $!"
	echo "Log:        ${LOGS_DIR}/br_dedicated_local_Ve_Bl_20.log"
	echo "Per-job logs: ${SLURM_LOG_DIR}/"
	echo "Stop watchdog: touch ${STOP_FILE}  (in-flight jobs keep running)"
fi
