"""PHASE -1: does stacking RAM frames let the agent TELL BRANCHES APART?

POLICY-FREE BY CONSTRUCTION. Earlier plans compared a 19.68M-step stack=1
checkpoint against a fresh stack=12 net, which confounds the treatment with
19.68M steps of training and with whatever pathology that checkpoint carries.
But the question -- "do the 484 joint actions at this state produce distinct
OBSERVATIONS?" -- is a property of the observation pipeline and the emulator.
The policy only decides which states you stand in. So this rolls ONE uniform-
random trajectory and re-samples it at every (k, stride) combination offline.
Same states, same branches, same emulator; only the stacking varies.

WHAT IS ACTUALLY BEING TESTED. An agent step advances num_step_frames = 8
emulator frames. Every branch of a state is restored from the SAME snapshot, so
every stacked frame older than 8 emulator frames is BYTE-IDENTICAL across all
484 branches and cannot distinguish them. Only the 8 frames generated by the
branch step itself carry branch information. Therefore:

    stride 8 (one sample per agent step)  ->  exactly ONE branch-specific frame,
                                              for ANY k. Stacking is INERT for
                                              branch distinguishability.
    stride s < 8                          ->  ceil(8/s) branch-specific frames.

That is a prediction, not a hedge, and this script checks it: the stride-8 row
must equal the k=1 row exactly for every k. If it does not, something is wrong
with the buffer and the whole sweep is void.

The point of the sweep is the OTHER half -- whether the sub-step frames actually
resolve anything the newest frame alone does not. A special move's active frames
last ~2-4 emulator frames, so stride 8 aliases them out entirely; if the missing
state is hitstun/startup phase, only stride < 8 can recover it.

REFERENCE ROWS, so the numbers have a scale:
  ram_truth   distinct md5 of FULL unmasked RAM. Ground truth: how many of the
              484 branches the GAME actually distinguishes. Nothing can beat it.
  pixel       distinct hash of the image observation -- what the CNN path sees.
              This is the A4 "median 1 distinct successor" measurement.
  k=1         distinct hash of one masked RAM frame. The current ram baseline.

READING IT. Gap between ram_truth and k=1 is the information the mask+sampling
throws away. If a (k, stride) row closes that gap, stacking is worth the 12.9M
parameters. If every row sits at k=1, the binding constraint is the MASK, not
the temporal window, and no amount of stacking will help.
"""
import argparse
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

ROOT_KEY = "preflight_root"

# Buffer must span the widest combo: (k-1)*stride + 1 emulator frames.
MAX_K = 12
MAX_STRIDE = 8


def _h(a):
    return hashlib.md5(np.ascontiguousarray(a)).hexdigest()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--state", default="Champion.Level1.RyuVsRyu.2Player")
    ap.add_argument("--ram_mask", default="ram_mask.npy")
    ap.add_argument("--n_roots", type=int, default=60)
    ap.add_argument("--warmup", type=int, default=30,
                    help="random agent steps before the first root")
    ap.add_argument("--gap", type=int, default=6,
                    help="random agent steps between roots")
    ap.add_argument("--ks", default="1,2,4,8,12")
    ap.add_argument("--strides", default="1,2,4,8")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--verify_roots", type=int, default=3,
                    help="roots on which the fast path is cross-checked against "
                         "a full recomputation. 0 disables -- do not.")
    ap.add_argument("--out", default="preflight_ram_stack.json")
    a = ap.parse_args(argv)

    global np
    import numpy as np
    from local_best_response import make_lbr_env

    ks = [int(x) for x in a.ks.split(",") if x.strip()]
    strides = [int(x) for x in a.strides.split(",") if x.strip()]
    if max(ks) > MAX_K or max(strides) > MAX_STRIDE:
        raise SystemExit(f"buffer is sized for k<={MAX_K}, stride<={MAX_STRIDE}")

    mask = np.load(a.ram_mask)
    rng = np.random.RandomState(a.seed)

    # stack=MAX_K, stride=MAX_STRIDE => depth (12-1)*8+1 = 89 CONTIGUOUS emulator
    # frames, because the tap appends every frame regardless of stride. One
    # rollout therefore supports every combo with (k-1)*stride <= 88.
    env = make_lbr_env(a.state, obs_type="ram", ram_mask=mask,
                       ram_stack=MAX_K, ram_stride=MAX_STRIDE, seed=a.seed)()
    cfg = env.lbr_config()
    na = cfg["n_actions"]
    if na is None:
        raise SystemExit(f"need a MultiDiscrete action space; got {cfg['action_space']}")
    nj = na * na
    print(f"[preflight] {na}x{na} = {nj} joint actions per state, "
          f"{a.n_roots} roots, buffer depth {(MAX_K-1)*MAX_STRIDE+1} emulator frames",
          flush=True)

    # Locate SFWrapper for the pixel reference row. NOT by hasattr-walking:
    # gym.Wrapper.__getattr__ forwards unknown names DOWN the chain, so
    # hasattr(outer, "num_step_frames") is already True and the walk stops at
    # the wrapper it started on. RamObsWrapper stores the real reference.
    sf = env._sf
    assert type(sf).__name__ == "SFWrapper", type(sf).__name__
    nsf = sf.num_step_frames
    if nsf != 8:
        print(f"[preflight] NOTE num_step_frames={nsf}, not 8; "
              f"branch-specific frame count is ceil({nsf}/stride)", flush=True)

    def rand_joint():
        return np.array([rng.randint(na), rng.randint(na)])

    env.reset()
    for _ in range(a.warmup):
        env.step(rand_joint())

    combos = [(k, s) for k in ks for s in strides]
    counts = {f"k{k}_s{s}": [] for k, s in combos}
    counts["ram_truth"] = []
    counts["pixel"] = []
    n_verified = 0

    for root in range(a.n_roots):
        env.lbr_snapshot(ROOT_KEY)
        # per-branch: hashes of the nsf frames the branch step itself generated,
        # newest first. Frames older than that are restored from the snapshot and
        # are identical across branches by construction.
        fresh = []
        truth = []
        pixel = []
        full = [] if n_verified < a.verify_roots else None
        for i in range(na):
            for j in range(na):
                env.lbr_restore(ROOT_KEY)
                env.step(np.array([i, j]))
                truth.append(hashlib.md5(
                    np.ascontiguousarray(env._retro.get_ram())).hexdigest())
                tail = env.ram_tail(nsf)              # oldest..newest
                fresh.append(tuple(_h(f) for f in tail[::-1]))   # newest first
                pixel.append(_h(sf._get_obs(np.asarray(sf.env.frames))))
                if full is not None:
                    full.append(env.ram_tail((MAX_K - 1) * MAX_STRIDE + 1))
        env.lbr_restore(ROOT_KEY)
        env.lbr_drop(ROOT_KEY)

        counts["ram_truth"].append(len(set(truth)))
        counts["pixel"].append(len(set(pixel)))
        for k, s in combos:
            # offsets back from the newest frame; only those < nsf are
            # branch-specific, the rest are shared and carry zero information.
            off = [i * s for i in range(k) if i * s < nsf]
            keys = set(tuple(fr[o] for o in off) for fr in fresh)
            counts[f"k{k}_s{s}"].append(len(keys))

        if full is not None:
            # CROSS-CHECK the fast path against a full recomputation of the actual
            # concatenated observation. A shared-prefix argument that is subtly
            # wrong would silently deflate every number in the table.
            for k, s in combos:
                idx = [(MAX_K - 1) * MAX_STRIDE - i * s for i in range(k)]
                direct = set(_h(np.concatenate([w[i] for i in reversed(idx)]))
                             for w in full)
                fast = counts[f"k{k}_s{s}"][-1]
                if len(direct) != fast:
                    raise SystemExit(
                        f"FAILED cross-check at root {root}, k={k} stride={s}: "
                        f"fast path says {fast} distinct, full recomputation says "
                        f"{len(direct)}. The shared-prefix argument is wrong and "
                        f"every number in this table is void.")
            n_verified += 1

        for _ in range(a.gap):
            env.step(rand_joint())
        if (root + 1) % 10 == 0:
            print(f"[preflight] {root+1}/{a.n_roots} roots", flush=True)

    if n_verified < min(a.verify_roots, a.n_roots):
        raise SystemExit(f"FAILED: cross-checked {n_verified} roots, expected "
                         f"{min(a.verify_roots, a.n_roots)}. A check that does not "
                         f"run is indistinguishable from one that passes.")
    env.close()

    def stat(v):
        v = np.asarray(v, dtype=np.float64)
        return dict(mean=float(v.mean()), median=float(np.median(v)),
                    p10=float(np.percentile(v, 10)), max=float(v.max()))

    res = {"config": vars(a), "n_joint": nj, "num_step_frames": nsf,
           "stats": {k: stat(v) for k, v in counts.items()},
           "raw": {k: list(map(int, v)) for k, v in counts.items()}}
    with open(a.out, "w") as f:
        json.dump(res, f, indent=2)

    print(f"\n  distinct successors out of {nj}, over {a.n_roots} roots "
          f"({n_verified} cross-checked against full recomputation)\n")
    print(f"  {'row':>12} {'mean':>8} {'median':>8} {'p10':>7} {'max':>6}")
    for row in ["ram_truth", "pixel"] + [f"k{k}_s{s}" for k, s in combos]:
        st = res["stats"][row]
        print(f"  {row:>12} {st['mean']:8.2f} {st['median']:8.1f} "
              f"{st['p10']:7.1f} {st['max']:6.0f}")

    # THE PREDICTION. Stride 8 samples once per agent step, so exactly one
    # stacked frame is branch-specific no matter how deep the stack -- the
    # stride-8 column must be flat in k. A violation means the buffer is not
    # doing what the docstring says.
    if 8 in strides and len(ks) > 1:
        base = counts[f"k{ks[0]}_s8"] if ks[0] == 1 else None
        if base is not None:
            for k in ks[1:]:
                if counts[f"k{k}_s8"] != base:
                    raise SystemExit(
                        f"FAILED: k={k} stride=8 differs from k=1 stride=8. Every "
                        f"frame but the newest is shared across branches at stride "
                        f"8, so these MUST be identical. The buffer is wrong.")
            print(f"\n  [ok] stride-8 column is flat in k, as predicted: stacking "
                  f"at agent-step\n       granularity is INERT for branch "
                  f"distinguishability.")

    tru = res["stats"]["ram_truth"]["mean"]
    k1 = res["stats"]["k1_s8"]["mean"] if "k1_s8" in res["stats"] else float("nan")
    best = max((res["stats"][f"k{k}_s{s}"]["mean"], k, s) for k, s in combos)
    print(f"\n  gap to close : ram_truth {tru:.2f} - k=1 {k1:.2f} = {tru-k1:.2f}")
    print(f"  best combo   : k={best[1]} stride={best[2]} -> {best[0]:.2f} "
          f"({(best[0]-k1)/max(tru-k1,1e-9):.1%} of the gap)")
    print(f"\n  wrote {a.out}")


if __name__ == "__main__":
    main()
