name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake zlib1g-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install gym-retro from GitHub
      run: |
        pip install git+https://github.com/openai/retro.git@v0.8.0

    - name: Install local stable-baselines3
      run: |
        pip install -e ./stable_baselines3

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "*.py"